name: ecommerceapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  firebase_auth: ^6.1.1
  shared_preferences: ^2.5.3
  font_awesome_flutter: ^10.9.1
  google_fonts: ^6.3.2
  lottie: ^3.3.1
  intl: ^0.20.2
  responsive_grid: ^2.4.4
  responsive_framework: ^1.5.1
  fl_chart: ^0.69.2
  feather_icons: ^1.2.0
  go_router: ^16.3.0
  dropdown_button2: ^2.3.9
  material_design_icons_flutter: ^7.0.7296
  syncfusion_flutter_charts: ^31.1.19
  iconsax_plus: ^1.0.0
  flutter_animate: ^4.5.2
  iconly: ^1.0.1
  table_calendar: ^3.2.0
  provider: ^6.1.5+1
  flutter_svg: ^2.2.1
  url_strategy: ^0.3.0
  flutter_localizations:
    sdk: flutter
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/widget_images/
    - assets/images/widget_images/banner_images/
    - assets/images/sidebar_icons/
    - assets/images/widget_images/dashboard_icon/
    - assets/images/widget_images/card_images/feature_card/
    - assets/images/widget_images/sm_icon/
    - assets/images/widget_images/authentication_images/
    - assets/images/widget_images/dashboard_overview_icon/
    - assets/images/widget_images/svg_icons/
    - assets/images/widget_images/not_found_images/
    - assets/images/widget_images/dashboard_overview_icon/ecommerce_admin_icons/
    - assets/images/widget_images/dashboard_overview_icon/ecommerce_admin_icons/category_icons/
    - assets/images/widget_images/dashboard_overview_icon/influencer_admin_icons/
    - assets/images/widget_images/dashboard_overview_icon/news_admin_icons/
    # static images
    - assets/images/static_images/
    - assets/images/static_images/ai_generated/images/
    - assets/images/static_images/avatars/person_images/
    - assets/images/static_images/avatars/placeholder_avatar/
    - assets/images/static_images/background_images/
    - assets/images/static_images/icons/crypto_icons/
    - assets/images/static_images/placeholder_images/random_placeholders/
    - assets/images/static_images/product_images/
    #socail icons
    - assets/images/static_images/icons/social_icons/
  #   - images/a_dot_ham.jpeg
    #country image
    - assets/images/widget_images/country_image/
    - assets/images/widget_images/delivery_dashboard_icons/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: KulimPark
      fonts:
        - asset: assets/fonts/KulimPark-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
